language: node_js
env:
  version:  1.0.0
node_js:
  - 14
stages:
  - install
  - run
jobs:
  - stage: "install & run"
    script: 
      - npm install
      - npm run cover
    after_success:
      - bash <(curl -s https://codecov.io/bash)