language: node_js
env:
  version:  1.0.0
node_js:
  - 14
stages:
  - install
  - run
jobs:
  - stage: "install & run"
    before_script: npm install -g pm2 codecov
    script: 
      - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
      - codecov
      - pm2 start app.js