language: node_js
env:
  version:  1.0.0
node_js:
  - 14
stages:
  - install
  - run
jobs:
  - stage: "install & run"
    script: 
      - npm install
      - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
      - codecov
    after_success:
      - bash <(curl -s https://codecov.io/bash)